/**
 * R scripting syntax v 1.1 
 * 
 * v1.1 by Adrian Pasculescu (2010/07/05)
 *   
**/
editAreaLoader.load_syntax["r_script"] = {
	'DISPLAY_NAME' : 'R scripting'
	,'COMMENT_SINGLE' : {1 : '#'}
	,'COMMENT_MULTI' : {}
	,'QUOTEMARKS' : {1: "'", 2: '"'}
	,'KEYWORD_CASE_SENSITIVE' : true
	,'KEYWORDS' : {
		/*
		** Set 1: reserved words
		** http://cran.r-project.org/doc/manuals/R-lang.pdf
		*/
		'reserved' : [
			'if', 'else', 'repeat', 'while', 'function', 'for', 'in', 'next', 'break',
			'TRUE', 'FALSE', 'NULL', 'Inf', 'NaN',
			'NA', 'NA_integer_', 'NA_real_', 'NA_complex_', 'NA_character_', '...'
		]
		/*
		** Set 2: builtins
		*/	
		,'builtins' : [
			'.C', '.Call', '.External'
			,'.Fortran' 
			,'.Internal' 
			,'.Primitive' 
			,'as.call'
			,'as.character' 
			,'as.function' 
			,'as.list'
			,'as.name'
			,'assign'
			,'attr' 
			,'attributes' 
			,'baseenv'
			,'basename' 
			,'body' 
			,'browser'
			,'debug' 
			,'dirname'
			,'do.call'
			,'emptyenv' 
			,'environment' 
			,'eval' 
			,'file.access' 
			,'file.append' 
			,'file.choose' 
			,'file.copy' 
			,'file.create' 
			,'file.exists' 
			,'file.info' 
			,'file.path' 
			,'file.remove' 
			,'file.rename' 
			,'file.show' 
			,'formals' 
			,'get' 
			,'is.na' 
			,'is.nan'
			,'match.arg' 
			,'match.call' 
			,'match.fun' 
			,'missing'
			,'mode' 
			,'names' 
			,'NaN' 
			,'new.env'
			,'NextMethod' 
			,'on.exit'
			,'pairlist' 
			,'path.expand' 
			,'proc.time' 
			,'quote' 
			,'stop' 
			,'storage.mode' 
			,'substitute' 
			,'switch'
			,'Sys.getenv' 
			,'Sys.getlocale'
			,'Sys.localeconv' 
			,'Sys.putenv' 
			,'Sys.putlocale'
			,'Sys.time' 
			,'Sys.timezone' 
			,'system'
			,'system.time' 
			,'trace' 
			,'traceback' 
			,'typeof' 
			,'undebug'
			,'unlink'
			,'untrace'
			,'UseMethod' 
			,'warning'
			,'warnings' 
		]
		/*
		** Set 3: standard library
		** http://stat.ethz.ch/R-manual/R-patched/library/lattice/html/00Index.html
		*/
		,'lattice' : [
			 'as.character.shingleLevel'
			,'as.data.frame.shingle'
			,'as.factorOrShingle'
			,'as.shingle'
			,'auto.key'
			,'axis.default'
			,'banking'
			,'barchart'
			,'barchart.array'
			,'barchart.default'
			,'barchart.formula'
			,'barchart.matrix'
			,'barchart.numeric'
			,'barchart.table'
			,'barley'
			,'bwplot'
			,'bwplot.formula'
			,'bwplot.numeric'
			,'canonical.theme'
			,'cloud'
			,'cloud.formula'
			,'cloud.matrix'
			,'cloud.table'
			,'col.whitebg'
			,'contourplot'
			,'contourplot.array'
			,'contourplot.formula'
			,'contourplot.matrix'
			,'contourplot.table'
			,'current.column'
			,'current.panel.limits'
			,'current.row'
			,'densityplot'
			,'densityplot.formula'
			,'densityplot.numeric'
			,'diag.panel.splom'
			,'dim.trellis'
			,'dimnames.trellis'
			,'do.breaks'
			,'dotplot'
			,'dotplot.array'
			,'dotplot.default'
			,'dotplot.formula'
			,'dotplot.matrix'
			,'dotplot.numeric'
			,'dotplot.table'
			,'draw.colorkey'
			,'draw.key'
			,'environmental'
			,'equal.count'
			,'ethanol'
			,'histogram'
			,'histogram.factor'
			,'histogram.formula'
			,'histogram.numeric'
			,'is.shingle'
			,'larrows'
			,'Lattice'
			,'lattice'
			,'lattice.getOption'
			,'lattice.options'
			,'latticeParseFormula'
			,'level.colors'
			,'levelplot'
			,'levelplot.array'
			,'levelplot.formula'
			,'levelplot.matrix'
			,'levelplot.table'
			,'llines'
			,'llines.default'
			,'lplot.xy'
			,'lpoints'
			,'lpoints.default'
			,'lpolygon'
			,'lrect'
			,'lsegments'
			,'lset'
			,'ltext'
			,'ltext.default'
			,'ltransform3dMatrix'
			,'ltransform3dto3d'
			,'make.groups'
			,'melanoma'
			,'oneway'
			,'packet.number'
			,'packet.panel.default'
			,'palette.shade'
			,'panel.3dscatter'
			,'panel.3dwire'
			,'panel.abline'
			,'panel.arrows'
			,'panel.average'
			,'panel.axis'
			,'panel.barchart'
			,'panel.brush.splom'
			,'panel.bwplot'
			,'panel.cloud'
			,'panel.contourplot'
			,'panel.curve'
			,'panel.densityplot'
			,'panel.dotplot'
			,'panel.error'
			,'panel.fill'
			,'panel.functions'
			,'panel.grid'
			,'panel.histogram'
			,'panel.identify'
			,'panel.identify.cloud'
			,'panel.identify.qqmath'
			,'panel.levelplot'
			,'panel.levelplot.raster'
			,'panel.linejoin'
			,'panel.lines'
			,'panel.link.splom'
			,'panel.lmline'
			,'panel.loess'
			,'panel.mathdensity'
			,'panel.number'
			,'panel.pairs'
			,'panel.parallel'
			,'panel.points'
			,'panel.polygon'
			,'panel.qq'
			,'panel.qqmath'
			,'panel.qqmathline'
			,'panel.rect'
			,'panel.refline'
			,'panel.rug'
			,'panel.segments'
			,'panel.smoothScatter'
			,'panel.splom'
			,'panel.stripplot'
			,'panel.superpose'
			,'panel.superpose.2'
			,'panel.superpose.plain'
			,'panel.text'
			,'panel.tmd.default'
			,'panel.tmd.qqmath'
			,'panel.violin'
			,'panel.wireframe'
			,'panel.xyplot'
			,'parallel'
			,'parallel.data.frame'
			,'parallel.formula'
			,'parallel.matrix'
			,'plot.shingle'
			,'plot.trellis'
			,'prepanel.default.bwplot'
			,'prepanel.default.cloud'
			,'prepanel.default.densityplot'
			,'prepanel.default.histogram'
			,'prepanel.default.levelplot'
			,'prepanel.default.parallel'
			,'prepanel.default.qq'
			,'prepanel.default.qqmath'
			,'prepanel.default.splom'
			,'prepanel.default.xyplot'
			,'prepanel.lmline'
			,'prepanel.loess'
			,'prepanel.qqmathline'
			,'prepanel.tmd.default'
			,'prepanel.tmd.qqmath'
			,'print.shingle'
			,'print.shingleLevel'
			,'print.trellis'
			,'qq'
			,'qq.formula'
			,'qqmath'
			,'qqmath.formula'
			,'qqmath.numeric'
			,'rfs'
			,'Rows'
			,'shingle'
			,'show.settings'
			,'simpleKey'
			,'simpleTheme'
			,'singer'
			,'splom'
			,'splom.data.frame'
			,'splom.formula'
			,'splom.matrix'
			,'standard.theme'
			,'strip.custom'
			,'strip.default'
			,'stripplot'
			,'stripplot.formula'
			,'stripplot.numeric'
			,'summary.shingle'
			,'summary.trellis'
			,'t.trellis'
			,'tmd'
			,'tmd.formula'
			,'tmd.trellis'
			,'trellis.currentLayout'
			,'trellis.device'
			,'trellis.focus'
			,'trellis.grobname'
			,'trellis.last.object'
			,'trellis.object'
			,'trellis.panelArgs'
			,'trellis.par.get'
			,'trellis.par.set'
			,'trellis.switchFocus'
			,'trellis.unfocus'
			,'trellis.vpname'
			,'update.trellis'
			,'utilities.3d'
			,'which.packet'
			,'wireframe'
			,'wireframe.formula'
			,'wireframe.matrix'
			,'xscale.components.default'
			,'xyplot'
			,'xyplot.formula'
			,'xyplot.ts'
			,'yscale.components.default'

		]
		/*
		** Set 4: special methods
		** this is for my favourite
		*/
		,'special' : [ 'url','str','print','data.frame','rbind','apply','sapply','tapply','mapply'
				,'mean','median','sd','plot',  'paste','sprintf','strsplit','unlist','gsub','grep'
		]
	}
	,'OPERATORS' :[
		'-', '+', '!', '~', '?', ':', '*', '/', '^', '%%', '%/%', '%*%', '%o%', '%x%', '%in%', '<', '>', '==',
		'>=', '<=', '&', '&&', '|', '||', '<-', '->', '$'
	]
	,'DELIMITERS' :[
		'(', ')', '[', ']', '{', '}'
	]
	,'STYLES' : {
		'COMMENTS': 'color: #AAAAAA;'
		,'QUOTESMARKS': 'color: #660066;'
		,'KEYWORDS' : {
			'reserved' : 'color: #0000FF;'
			,'builtins' : 'color: #F58A1F;'
			,'lattice' : 'color: #009900;'
			,'special': 'color: #DE11DE;'
			}
		,'OPERATORS' : 'color: #993300;'
		,'DELIMITERS' : 'color: #993300;'
				
	}
};
